openapi: 3.0.1
info:
  title: master-data:master-clients
  description: >
    API for master clients - both reading existing master clients and creating
    new master clients is supported. However, updating or deleting existing
    master clients is not yet supported.

    The master client entity is used across multiple DATEV business applications
    to represent common master data entities such as companies or natural
    persons. The master client entity provides data attributes such as
    identification attributes (like names), contact data (phone, e-mail, postal
    address) and other attributes that are required by DATEV or third party
    business applications.


    The master client entity is most commonly used to represent clients
    (customers) of DATEV members, but its use is not restricted to that business
    role.


    Each master client entity is contained in exactly one __data environment__.
    Each data environment is owned and controlled by exactly one __business
    partner__ (such as a tax consultant or a lawyer that is a  DATEV member).


    Data describing the legal person (such as a company) and/or the natural
    person can be accessed as embedded subresources of the "master-clients"
    primary resource. At least one of both subresources (legal and/or natural
    person) is guaranteed to be present. These are sometimes referred to as the
    *"client addressees"*.


    By default, both addressee subresources are __not__ embedded in the
    "master-clients" resource. If you want to retrieve the addressee
    subresources, an explicit "expand" parameter must be used as explained
    further down.


    In addition to master client entities, basic information about the current
    user's business partner can be retrieved through the "org-info" resource
    together with the "data-environments" resource.


    Starting with version 3 of the API a number of attributes of master clients
    and addressees are administered as "historical". This means that these
    attributes are provided as lists or arrays which hold both the current valid
    and all previous and/or future values of a specific attribute. It's possible
    to derive time periods from historically administered attributes that
    indicate the validity range of a particular value.


    This is best illustrated by the following example:


    ```json

    "job_titles": [
      { "value":"Müller" },
      { "value":"Bäcker",  "valid_from":"1995-04-01" },
      { "value":"Metzger", "valid_from":"2001-07-01" }
    ]

    ```


    In this example, the profession "Müller" ("miller") was valid until
    03/31/1995.  

    "Bäcker" ("baker") was valid from 04/01/1995 to 06/30/2001.  

    The value "Metzger" ("butcher") is valid starting 07/01/2001.  


    For all historically administered attributes, there is an additional
    property that indicates the current valid value (the value that is valid
    today/as of the system time). The names of these attributes are all prefixed
    with "current". In the example above, the property name is
    "current_job_title" with the value "Metzger".
  license:
    name: DATEV eG
    url: https://www.datev.de
  version: '3.1'
  x-ibm-name: master-data-master-clients
servers:
  - url: https://master-data-master-clients.api.datev.de/platform/v3
  - url: https://master-data-master-clients.api.datev.de/platform-sandbox/v3
tags:
  - name: app
    description: Read or configure meta data about API consumer access.
  - name: org-info
    description: Read organization information.
  - name: master-clients
    description: Read master clients
paths:
  /apps:
    put:
      tags:
        - app
      summary: >-
        Update meta data about API consumer access, e.g. the schema of the
        returned master clients (contexts & bricks). Currently only available in
        sandbox.
      operationId: updateApp
      security:
        - datev_openid_sandbox:
            - datev:master-data:master-clients:read
          client_id: []
          client_secret: []
        - datev_openid_sandbox:
            - datev:master-data:master-clients:read
          client_id: []
  /master-clients/search:
    post:
      tags:
        - master-clients
      summary: Returns a list of master clients. Provides extended search abilities.
      description: >-
        Returns a list of all master clients that can be accessed by the user.
        Extended search parameters can be provided in the request body.
      operationId: search
      security:
        - datev_openid:
            - datev:master-data:master-clients:read
          client_id: []
          client_secret: []
        - datev_openid_sandbox:
            - datev:master-data:master-clients:read
          client_id: []
          client_secret: []
        - datev_openid:
            - datev:master-data:master-clients:read
          client_id: []
        - datev_openid_sandbox:
            - datev:master-data:master-clients:read
          client_id: []
  /master-clients/{master-client-id}:
    get:
      tags:
        - master-clients
      summary: Retrieve a specific master client.
      description: Returns a specific master client which the user has access to.
      operationId: findByZmoId
      security:
        - datev_openid:
            - datev:master-data:master-clients:read
          client_id: []
          client_secret: []
        - datev_openid_sandbox:
            - datev:master-data:master-clients:read
          client_id: []
          client_secret: []
        - client_secret: []
          client_id: []
        - datev_openid:
            - datev:master-data:master-clients:read
          client_id: []
        - datev_openid_sandbox:
            - datev:master-data:master-clients:read
          client_id: []
    head:
      tags:
        - master-clients
      summary: Retrieve meta data for a specific master client.
      description: >-
        Returns meta data in form of headers for a specific master client which
        the user has access to.
      operationId: peekByZmoId
      security:
        - datev_openid:
            - datev:master-data:master-clients:read
          client_id: []
          client_secret: []
        - datev_openid_sandbox:
            - datev:master-data:master-clients:read
          client_id: []
          client_secret: []
        - datev_openid:
            - datev:master-data:master-clients:read
          client_id: []
        - datev_openid_sandbox:
            - datev:master-data:master-clients:read
          client_id: []
  /master-clients/{master-client-id}/consultant-client:
    get:
      tags:
        - master-clients
      summary: Retrieve the consultant client for a specific master client.
      description: >-
        Returns the consultant client for a specific master client. The user
        must have access to the master client as well as the consultant client.
        The consultant client is retrieved by resolving the assigned
        establishment of the master client. If a consultant client is assigned
        to the establishment, the consultant client is returned. Otherwise, the
        consultant client of the organization containing the establishment is
        returned, or, if neither is present, nothing is returned.
      operationId: findConsultantClientByClientZmoId
      security:
        - datev_openid:
            - datev:master-data:master-clients:read
          client_id: []
          client_secret: []
        - datev_openid_sandbox:
            - datev:master-data:master-clients:read
          client_id: []
          client_secret: []
        - datev_openid:
            - datev:master-data:master-clients:read
          client_id: []
        - datev_openid_sandbox:
            - datev:master-data:master-clients:read
          client_id: []
    head:
      tags:
        - master-clients
      summary: >-
        Retrieve meta data for the consultant client of a specific master
        client.
      description: >-
        Returns meta data in form of headers for the consultant client of a
        specific master client which the user has access to.
      operationId: peekConsultantClientByClientZmoId
      security:
        - datev_openid:
            - datev:master-data:master-clients:read
          client_id: []
          client_secret: []
        - datev_openid_sandbox:
            - datev:master-data:master-clients:read
          client_id: []
          client_secret: []
        - datev_openid:
            - datev:master-data:master-clients:read
          client_id: []
        - datev_openid_sandbox:
            - datev:master-data:master-clients:read
          client_id: []
  /org-info:
    get:
      tags:
        - org-info
      summary: Returns business partner information.
      description: >-
        Returns information about the business partners the current user has
        access to and their data environments.
      operationId: getInfo
      security:
        - datev_openid:
            - datev:master-data:org-info:read
          client_id: []
          client_secret: []
        - datev_openid_sandbox:
            - datev:master-data:org-info:read
          client_id: []
          client_secret: []
        - datev_openid:
            - datev:master-data:org-info:read
          client_id: []
        - datev_openid_sandbox:
            - datev:master-data:org-info:read
          client_id: []
  /master-clients:
    get:
      tags:
        - master-clients
      summary: Returns a list of master clients.
      description: Returns a list of all master clients that can be accessed by the user.
      operationId: findAll
      security:
        - datev_openid:
            - datev:master-data:master-clients:read
          client_id: []
          client_secret: []
        - datev_openid_sandbox:
            - datev:master-data:master-clients:read
          client_id: []
          client_secret: []
        - datev_openid:
            - datev:master-data:master-clients:read
          client_id: []
        - datev_openid_sandbox:
            - datev:master-data:master-clients:read
          client_id: []
  /master-clients/{master-client-id}/corporate-structure:
    get:
      tags:
        - master-clients
      summary: Retrieve a corporate structure for a specific master client.
      description: >-
        Returns a corporate structure for a specific master client which the
        user has access to.
      operationId: findCorporateStructureByZmoId
      security:
        - datev_openid:
            - datev:master-data:org-info:read
          client_id: []
          client_secret: []
        - datev_openid_sandbox:
            - datev:master-data:org-info:read
          client_id: []
          client_secret: []
        - datev_openid:
            - datev:master-data:org-info:read
          client_id: []
        - datev_openid_sandbox:
            - datev:master-data:org-info:read
          client_id: []
  /legal-forms:
    get:
      tags:
        - master-clients
      summary: Returns a list of all available legal forms.
      description: >-
        Returns a list of all available legal forms which may be referenced by
        legal persons.
      operationId: getLegalForms
  /data-environments/{number}:
    get:
      tags:
        - org-info
      summary: Returns a data environment.
      description: Returns a specific data environment which the user has access to.
      operationId: findByNumber
      security:
        - datev_openid:
            - datev:master-data:org-info:read
          client_id: []
          client_secret: []
        - datev_openid_sandbox:
            - datev:master-data:org-info:read
          client_id: []
          client_secret: []
        - client_secret: []
          client_id: []
        - datev_openid:
            - datev:master-data:org-info:read
          client_id: []
        - datev_openid_sandbox:
            - datev:master-data:org-info:read
          client_id: []
  /country-codes:
    get:
      tags:
        - master-clients
      summary: Returns a list of all available country codes.
      description: >-
        Returns a list of all available country codes which may be referenced by
        addresses.
      operationId: getCountryCodes
components:
  securitySchemes:
    datev_openid_sandbox:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.datev.de/openidsandbox/authorize
          tokenUrl: https://sandbox-api.datev.de/token
          scopes:
            openid: Required for OIDC
            datev:master-data:master-clients:read: Read client master data
            datev:master-data:org-info:read: >-
              Read office and data environment labels as well as corporate
              structures
      x-ibm-oauth-provider: datev-openid-sandbox
    client_secret:
      type: apiKey
      name: X-DATEV-Client-Secret
      in: header
      x-key-type: client_secret
    datev_openid:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.datev.de/openid/authorize
          tokenUrl: https://api.datev.de/token
          scopes:
            openid: Required for OIDC
            datev:master-data:master-clients:read: Read client master data
            datev:master-data:org-info:read: >-
              Read office and data environment labels as well as corporate
              structures
      x-ibm-oauth-provider: datev-openid
    client_id:
      type: apiKey
      name: X-DATEV-Client-Id
      in: header
      x-key-type: client_id
x-ibm-configuration:
  type: rest
  phase: realized
  enforced: true
  testable: true
  cors:
    enabled: false
  application-authentication:
    certificate: false
  oauth-servers:
    datev_openid:
      authorizationCode:
        tokenUrls:
          - https://api.datev.de/token
        authorizationUrls:
          - https://login.datev.de/openid/authorize
        refreshUrls: []
    datev_openid_sandbox:
      authorizationCode:
        tokenUrls:
          - https://sandbox-api.datev.de/token
        authorizationUrls:
          - https://login.datev.de/openidsandbox/authorize
        refreshUrls: []
security:
  - datev_openid:
      - openid
    client_id: []
    client_secret: []
  - datev_openid_sandbox:
      - openid
    client_id: []
    client_secret: []
  - datev_openid:
      - openid
    client_id: []
  - datev_openid_sandbox:
      - openid
    client_id: []
x-ibm-endpoints:
  - url: https://master-data-master-clients.api.datev.de/platform/v3
  - url: https://master-data-master-clients.api.datev.de/platform-sandbox/v3
