from enum import Enum

class MasterClientFullAddresseeDetailTitleOfNobility(str, Enum):
    BARON = "Baron"
    BARONESSE = "Baronesse"
    BARONIN = "Baronin"
    BRAND = "Brand"
    CONDESA = "Condesa"
    EARL = "Earl"
    EDLE = "Edle"
    EDLER = "Edler"
    ERBGRAF = "Erbgraf"
    ERBPRINZ = "Erbprinz"
    FREIFRAU = "Freifrau"
    FREIHERR = "Freiherr"
    FREIIN = "Freiin"
    FÜRST = "Fürst"
    FÜRSTIN = "Fürstin"
    GRAF = "Graf"
    GROSSHERZOG = "Großherzog"
    GROSSHERZOGIN = "Großherzogin"
    GRÄFIN = "Gräfin"
    HERZOG = "Herzog"
    HERZOGIN = "Herzogin"
    LANDGRAF = "Landgraf"
    LANDGRÄFIN = "Landgräfin"
    MARQUES = "Marques"
    MARQUIS = "Marquis"
    MARSCHALL = "Marschall"
    OSTOJA = "Ostoja"
    PRINZ = "Prinz"
    PRINZESSIN = "Prinzessin"
    REICHSGRAF = "Reichsgraf"
    REICHSGRÄFIN = "Reichsgräfin"
    RITTER = "Ritter"
    TRUCHSESS = "Truchsess"

    def __str__(self) -> str:
        return str(self.value)
