from enum import Enum

class ProblemDetailsReason(str, Enum):
    DATA_ENVIRONMENT_NOT_FOUND = "DATA_ENVIRONMENT_NOT_FOUND"
    MASTER_CLIENT_ID_ALREADY_ASSIGNED = "MASTER_CLIENT_ID_ALREADY_ASSIGNED"
    MASTER_CLIENT_NUMBER_INVALID = "MASTER_CLIENT_NUMBER_INVALID"
    MASTER_CLIENT_NUMBER_UNUSABLE = "MASTER_CLIENT_NUMBER_UNUSABLE"
    NO_APP_GRANTS = "NO_APP_GRANTS"
    NO_DATA_ENVIRONMENTS = "NO_DATA_ENVIRONMENTS"
    NO_USER_PERMISSIONS = "NO_USER_PERMISSIONS"
    UNKNOWN_CLIENT_ID = "UNKNOWN_CLIENT_ID"
    VALIDATION_FAILED = "VALIDATION_FAILED"

    def __str__(self) -> str:
        return str(self.value)
