from enum import Enum

class GetDocumentMetadataDocumentTypes(str, Enum):
    AANB_ABEG_BUBE_DAWE_KBNW_KOST_KOTR_LKTO_LOBN_LJOE_LOJE_LOJO_LOPE_LOPN_LOPS_LORE_LOWE_LSTA_LSTB_LSTE_PDAT_PFAN_PRZA_SBNW_SVNW_WEAN_ZABR_ZAKF_ZAUW = "AANB, ABEG, BUBE, DAWE, KBNW, KOST, KOTR, LKTO, LOBN, LJOE, LOJE, LOJO, LOPE, LOPN, LOPS, LORE, LOWE, LSTA, LSTB, LSTE, PDAT, PFAN, PRZA, SBNW, SVNW, WEAN, ZABR, ZAKF, ZAUW"

    def __str__(self) -> str:
        return str(self.value)
